### PR TITLE
Create jetbrains.json

### PR DESCRIPTION
**Pull request by maartenba**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [x] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [x] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [x] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Review by DeeJayTC — CHANGES_REQUESTED** [review]
Hey @maartenba 
Couple of things....

First of all we don't add company blogs, or only if you have content that's dedicated towards .NET and not talking about your products. If you want to talk about sponsoring opportunities to have some of your posts listed we can talk about that. 

Also the JSON you sent us is not even close to the correct format we are  using.

**Comment by DeeJayTC** [comment]
Yea sorry, thats missleading on our end. The company card layout is old and we did not remove it yet you just have to use the normal one in content-creators. 

If you can give us a filtered blog feed that only contains .NET-related content without any company product posts in there we could potentially add that but we would prefer that all your author's signup individually with their individual RSS link if you have that. I can see that you have individual pages -> https://blog.jetbrains.com/author/khalid-abuhakmeh/ are there feeds for the individual authors as well?

**Comment by maartenba** [comment]
That would be https://blog.jetbrains.com/author/khalid-abuhakmeh/feed/ but no guarantee it will all be product-free. FTR I'm OK with closing this PR and not merging :-)

**Comment by DeeJayTC** [comment]
Yep ok, as said were still looking into funding options and also how we can add companies actkve in .NET Ecosystem to our page but we are not there yet. Feel free to reach out if you want to support us anytime. 

As of now with only 2 exceptions (Official .NET feeds and Orchard CMS which is open source) we only have individuals listed.

**Comment by maartenba** [comment]
Cool, thanks @DeeJayTC ! (also can you send me an email on maarten at jetbrains .com?)

**Pull request closed without merging**
