### PR TITLE
Update feeds Urls

### PR DESCRIPTION
**Pull request by adansari**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [x] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [x] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [x] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Are both feeds pure dotnet feeds or personal feeds? We got a new notation in the latest template that sets the feed.type either to personal or dotnet.

**Comment by matthiasjost** [comment]
See also the new PR template for clarification: https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by adansari** [comment]
Both are dotnet feeds, however if only one dotnet feed is allowed then please consider the blogspot one. I dont have personal type feed yet.

**Comment by adansari** [comment]
Updated the PR to have only one dotnet feed

**Comment by matthiasjost** [comment]
As many as you want are allowed set the type to dotnet or personal or both to dotnet if they are dotnet.
The meaning of type has changed.
See example card file and guidelines.

**Comment by adansari** [comment]
Thanks Matt for clarification, updates my card json

**Pull request merged**
