### PR TITLE
Update Saeed-Esmaeelinejad info

### PR DESCRIPTION
**Pull request by sa-es-ir**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [] There must be three content pieces in English. 

* [] There needs to be more than tweets. 

* [] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [ ] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [ ] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [ ] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [ ] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Thanks, @sa-es-ir! Could you check all the boxes that apply so that we know your feed qualifies for the platform? Greetings Matthias

**Comment by sa-es-ir** [comment]
@matthiasjost thanks and checkboxes updated

**Comment by matthiasjost** [comment]
Can you point me to the channel (and also add it to the card) that fulfills this?

"You must have published at least three content pieces (long form content) since 2022 on any of your channels."

**Comment by sa-es-ir** [comment]
@matthiasjost I think I made a mistake for checkboxes, I don't have any channel (yet), I usually post on LinkedIn like this one which was published yesterday:
https://www.linkedin.com/posts/sa-es-ir_middleware-data-transferring-activity-7066661530687213569-BMJF?utm_source=share&utm_medium=member_desktop

Also checkboxes updated.

**Comment by matthiasjost** [comment]
We cannot accept you as a creator with less than 3 content items.

**Pull request closed without merging**
