### PR TITLE
Add Aditya Oberai's creator card

### PR DESCRIPTION
**Pull request by adityaoberai**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [x] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [x] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [x] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by adityaoberai** [comment]
I have actively streamed with Microsoft Reactor and various other channels on content around .NET, as well as spoken at C# Corner's Conference.

- https://www.youtube.com/watch?v=6xGMqv71RKI&ab_channel=MicrosoftReactor
- https://www.youtube.com/watch?v=bgIkcajXOHk&ab_channel=MicrosoftReactor
- https://www.youtube.com/watch?v=VzHhevtNjb8&ab_channel=MicrosoftReactor
- https://www.youtube.com/watch?v=avEIIpRsB-w&ab_channel=MajorLeagueHacking
- https://www.youtube.com/watch?v=aZ62fcJM2VM&ab_channel=MajorLeagueHacking
- https://www.youtube.com/watch?v=lrGl6Iz27Kw&ab_channel=C%23Corner

**Comment by matthiasjost** [comment]
Hey. thanks for your submission. 

Do you have some main channel like a blog with an RSS feed?

What I saw was a collection of links to other platforms.

That cannot really be integrated well.

Also if you you would still like to go ahead you would need to switch to the new card format: https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

**Comment by adityaoberai** [comment]
Right now, it's a bit mixed, but I can set up something dedicated soon.

I'll do that and port over my card to the new template after.

**Comment by matthiasjost** [comment]
Any updates on this @adityaoberai?

**Comment by matthiasjost** [comment]
I am closing this PR @adityaoberai. Please open a new one if you like.

**Comment by adityaoberai** [comment]
Hi Matthias
Extremely sorry, the review entirely slipped through my notifications.

I'll create a dedicated page and make an update sometime in the near future.

**Comment by matthiasjost** [comment]
Hey @adityaoberai No worries. Your PR is welcome at any time. Greetings Matthias

**Pull request closed without merging**
