### PR TITLE
Create aneesh-gopalakrishnan.json

### PR DESCRIPTION
**Pull request by codehippie1**
# #WeAreDonet Creator Submission Guidelines

* By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* We do not accept submissions with the sole intention of promoting a product or company.

* We add you as a creator, not your company. 

* The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* You must have published a post since 2022 on any of your channels. 

* There must be one publication in English. 

* There needs to be more than tweets. 

* A longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* If you do not submit an RSS or Atom URL. We cannot consider your feed for the upcoming aggregation feature. 

## Content Guideline 

* If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Review by DeeJayTC — CHANGES_REQUESTED** [review]
Hey @codehippie1 
while we can merge your request your content won't be visible in quite a while. 
We're not ready yet to support meetup or other community/user group channels. 

Happy to merge you but any chance you have a RSS feed, maybe for your blog? With .NET Content?

**Comment by codehippie1** [comment]
Sending updates as pert @DeeJayTC's suggestions

**Comment by codehippie1** [comment]
@DeeJayTC - No RSS feeds yet. But instead of meetup links, I can provide the direct youtube links (The events went live using .NET Foundation's youtube channel)

I updated the blog link with this - https://www.red-gate.com/simple-talk/development/angular/inline-pdf-viewer-in-an-angular-app-now-you-can/
The blog post has a section for asp.net usage under "A sample API using C# and ASP.NET Core" 

PS: I created the PDF library to fill in the gap when Asp.net core removed support for RDLC Report viewer
Link - https://learn.microsoft.com/en-us/archive/blogs/sqlrsteamblog/microsoft-acquires-report-rendering-technology-from-forerunner-software
Link: https://stackoverflow.com/questions/49309797/rdlc-local-report-viewer-for-asp-net-core-and-angular2-0

**Comment by codehippie1** [comment]
@DeeJayTC I will set up a feed and let you know.

**Comment by codehippie1** [comment]
@DeeJayTC - I have setup a RSS feed here: https://rss.app/feeds/79Dl0OyyexNBxDuA.xml

I added links to the feeds (youtube links and such). Let me know if this would suffice.

**Comment by DeeJayTC** [comment]
Yea that looks fine on first glance, i'll check it in detail later and merge it

**Pull request merged**
