### PR TITLE
Create victor-garcia.json

### PR DESCRIPTION
**Pull request by vhugogarcia**
Added myself as creator. Thank you!

### CODE REVIEW

**Review by DeeJayTC — CHANGES_REQUESTED** [review]
Hey Victor, can you please sign up on the website first?
https://www.wearedotnet.io 

We can't approve your PR if you're not signed up sadly.

**Comment by vhugogarcia** [comment]
Thanks @DeeJayTC for the feedback. I just registered and submitted my social info on the page. 😀

**Comment by vhugogarcia** [comment]
image

**Comment by DeeJayTC** [comment]
Yep! 👍

**Comment by DeeJayTC** [comment]
image
Sorted :9

**Pull request merged**
