### PR TITLE
Update chris-sainty.json

### PR DESCRIPTION
**Pull request by chrissainty**
Updated by RSS feed as it was pointing to the wrong place. Plus some general improvements to my card.

### CODE REVIEW

**Comment by matthiasjost** [comment]
@chrissainty Hey Chris, thanks for the update. Would you mind updating to the latest format? https://github.com/casals/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

Thanks and Greetings

Matthias

**Comment by chrissainty** [comment]
@matthiasjost I've updated the card to the new format. Let me know if there are any other issues.

**Comment by chrissainty** [comment]
Hey @matthiasjost when will the site update with the new info?

**Comment by matthiasjost** [comment]
It should have happened by two hours after the merge, but it didn't.
I will look at this together with Tim.

**Comment by chrissainty** [comment]
Any joy with this?

**Comment by matthiasjost** [comment]
Any news on this @DeeJayTC?

**Comment by DeeJayTC** [comment]
Yea, have to rebuild the index and have it reload a few of the creators. Hopefully got time to do that tomorrow or monday.

**Pull request merged**
