### PR TITLE
Create steve-bilogan.json

### PR DESCRIPTION
**Pull request by kazo0**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [ ] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [ ] There must be three content pieces in English. 

* [ ] There needs to be more than tweets. 

* [ ] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [ ] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [ ] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [ ] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [ ] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [ ] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [ ] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [ ] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [ ] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [ ] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Hey @kazo0, Thanks for your submission!
While I checked your blog, I tried looking for long-form content pieces since 2022. Please see the checklist where you will find the criteria for your creator submission.
Greetings
Matthias

**Comment by matthiasjost** [comment]
Hey @kazo0, are there any updates for this, or may I close the PR for now?

Greetings

Matthias

**Comment by kazo0** [comment]
@matthiasjost ah ok so I need content dating back to 2022 currently? Ok once I have more content on my blog I will make a new PR at a later date, this one can be closed :)

Thanks for the review!

**Comment by matthiasjost** [comment]
@kazo0 You are welcome.

Here is the description:
"You must have published at least three content pieces (long-form content) since 2022 on any of your channels."

So, if all three content pieces are from this year, it is also good. They just cannot be older than 2022.

And they would need to be in English as of now.

**Comment by matthiasjost** [comment]
@kazo0 Please excuse me. I made a mistake while reviewing. It seems you already published a lot. We can of course, accept your submission.

**Comment by matthiasjost** [comment]
@kazo0 You have been activated as a creator and should see your blog items very soon on your profile page: https://www.wearedotnet.io/kazo0

**Pull request merged**
