### PR TITLE
Create raul-piraces.json

### PR DESCRIPTION
**Pull request by piraces**
Add myself as creator 👍

### CODE REVIEW

**Review by DeeJayTC — CHANGES_REQUESTED** [review]
Hey Raul, can you please give us an RSS link that's filtered to your .NET content? WeAreDotnet is supposed to be 100% .NET content and its tough for us to filter out unrelated content from the feeds.

**Comment by piraces** [comment]
Hey @DeeJayTC , thanks for the feedback. I have just published a new feed with only 100% .NET entries and updated it in the json file. Therefore the content will be filtered on my side 👍 

You can check out the new feed in: https://piraces.dev/feed/dotnet.xml

**Comment by DeeJayTC** [comment]
Perfect, thanks a lot :) 
You're tagged as creator now. 

(you can't see this anywhere right now except in the member list if you're within the last 100 but we'll have that sooooon!)

**Comment by piraces** [comment]
Awesome! Thank you very much!

**Pull request merged**
