### PR TITLE
Create vicente-guzman.json

### PR DESCRIPTION
**Pull request by LucioMSP**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [x] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [x] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [x] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Hey @LucioMSP please use the latest card format for new submissions: https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

Greetings

Matthias

**Comment by matthiasjost** [comment]
I didn't hear anything. Could you use the new format?

**Comment by matthiasjost** [comment]
any updates on this @LucioMSP?

**Comment by LucioMSP** [comment]
> any updates on this @LucioMSP?

Done, can u check?

**Comment by matthiasjost** [comment]
Where do I find the three content pieces in English since 2022?

**Comment by matthiasjost** [comment]
Any updates on this Vinncente (@LucioMSP)?

**Comment by LucioMSP** [comment]
Hi @matthiasjost - You can find the code examples here: https://vicenteguzman.com/ia/ai/2023-05-13-chatbot-chatgpt-csharp/

**Comment by matthiasjost** [comment]
@LucioMSP Right now, we can only accept English content.

**Comment by matthiasjost** [comment]
@LucioMSP Do you agree on closing the PR for now? You are still very welcome in the community and on Discord, etc. It is just that we currently cannot process languages other than English for the three long form content pieces.

So, having other languages is still perfectly fine (as long as it is not in the main RSS/atom feed).

There must be three English long from content pieces.

**Comment by LucioMSP** [comment]
These don't count? 

https://www.syncfusion.com/blogs/author/luciomspgeeks-ms

**Comment by matthiasjost** [comment]
@LucioMSP Thanks. That definitely counts! So there is nothing in the way of approving your submission. Congratulations 🎉

**Comment by LucioMSP** [comment]
Thanks!

**Pull request merged**
