### PR TITLE
Adding Xavier Abelaira Rueda (Xelit3) creator card

### PR DESCRIPTION
**Pull request by Xelit3**
# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [X] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors

* [x] The content with feed.type = dotnet must be .NET related:
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [X] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [X] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [X] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [X] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [X] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [X] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Thanks for your submission. Can you use the latest format? https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json

Greetings

Matthias

**Comment by Xelit3** [comment]
> Thanks for your submission. Can you use the latest format? https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/_creatorTemplate.json
> 
> Greetings
> 
> Matthias

Hi @matthiasjost !

Thanks for reviewing it, I have submited now the latest format, but I have a couple of doubts:
- How can I link other social accounts like Twitter or LinkedIn? The template didn't clarify it 🙁
- I've marked my feed as dotnet, but I'm not fully clear about if I have to mark as dotnet or personal.

Many thanks in advance!

**Comment by matthiasjost** [comment]
Hey @Xelit3!

 In order to link your other accounts you can just login on the platform itself.
The rule for personal is, you may want to choose it if you post content that isn't about dotnet.
Some people have therefore multiple feeds.

I hope that clarifies your questions. Don't hesitate to ask again if there is something else we can do or answer for you.

Greetings

Matthias

**Comment by Xelit3** [comment]
Great then! Thanks for clarifying it @matthiasjost !

Is then ok the current card?

**Pull request merged**
