### PR TITLE
Adding card for Orchard Dojo

### LINKED ISSUE #91: Blog with multiple authors?
Under [Orchard Dojo](https://orcharddojo.net/) we have a blog with news about, and tutorials related to the open-source ASP.NET Core CMS and framework [Orchard Core](https://orchardcore.net/) (does it ring a bell, @matthiasjost? :)). Is this something suitable to be included on WeAreDotnet, or are only single-person blogs and else allowed?

While the Readme suggests the latter, [the other-cards](https://github.com/WeAreDotnet/dotnet-creator-cards/tree/main/other-cards) folder has a lot of similar multi-author blogs.

### PR DESCRIPTION
**Pull request by Piedone**
Please note the following:

- While I did read the docs, that only partially covers such non-person cards. So, based on that, the discussion under https://github.com/WeAreDotnet/dotnet-creator-cards/issues/91, and existing similar cards, I tried to come up with something sensible. Let me know if it doesn't make sense.
- I was confused, because the docs said to use a `feed` with `type` `"dotnet"` but none of the examples I see in the repo are like that.
- I added social links, but those are not for Orchard Dojo specifically, but for the parent company Lombiq. These do publish content from and for Orchard Dojo, but not just that. Let me know if they're suitable.

Fixes #91.

# #WeAreDonet Creator Submission Guidelines

* [x] Check all points before submitting the PR.

* [x] By submitting this pull request to add my creator card, I verify that I adhere to the #WeAreDotnet creator card submission guidelines.

* [x] Make sure to follow our [Code of Conduct](https://github.com/wearedotnet/dotnet-creator-cards/blob/master/CODE_OF_CONDUCT.md) 

* [x] We do not accept submissions with the sole intention of promoting a product or company.

* [x]  We add you as a creator, not your company. 

* [x]  The moderator team decides whether we accept or reject a submission.

## When Do We Accept Someone's Creator Card Submission? 

* [x] You must have published at least three content pieces (long form content) since 2022 on any of your channels. 
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] There must be three content pieces in English. 

* [x] There needs to be more than tweets. 

* [x] Longer-form article on LinkedIn is good, but a self-hosted blog or one on a well-known platform like Hashnode, medium etc., is better. 

* [x] Alternatively, you contributed with another form on a platform like YouTube, Twitch, Udemy or Pluralsight. If you have some recorded talks of conferences or anywhere else, that counts too! So in the form of a recorded video or a book. 

## RSS or Atom Feed 

* [x] The feed was validated using https://validator.w3.org/feed/ and does not contain errors - It did provide non-error recommendations though.

* [ ] The content with feed.type = dotnet must be .NET related: - The whole feed is .NET-related, but see my note at the top.
* .NET itself
* .NET libraries and projects
* .NET languages C#, F#, Visual Basic
* Tools needed during development (for .NET)
* CI/CD
* Only in combination with .NET: SPA Frontend technologies like Angular, Vue.js, React etc. 
* Cloud services related to .NET applications (AWS, Azure...)

* [x] the content under feed.type = personal may contain off-topic posts.
* Project management
* leadership
* Other

* [x] Submit an Atom or RSS URL inside your creator card that belongs to your blog 

* [x] If you do not submit an RSS or Atom URL. We cannot consider your feed for the aggregation feature. 

## Content Guideline 

* [x] If you have a self-hosted blog, please ensure you have a valid HTTPS certificate. 

* [x] We host NO malicious or offensive content on the blog (including photos, swearing, etc.)

* [x] You must add the full URL to your GitHub profile to your card, so we can assign it to the member account that used the same GitHub account for sign-up.

### CODE REVIEW

**Comment by matthiasjost** [comment]
dotnet and personal are feed types that are used to distinguish between the two.
personal may contain off-topic stuff and is only shown on the profile itself.

**Comment by DeeJayTC** [comment]
Ill have a look later today

**Comment by Piedone** [comment]
Thanks! I mostly tried to follow the .NET card you mentioned under the issue.

**Comment by DeeJayTC** [comment]
Is this your "main" github org?  --> https://github.com/OrchardCMS

**Comment by Piedone** [comment]
No, I'm not submitting a card for Orchard, the project and community. The card is for [Orchard Dojo](https://orcharddojo.net/), a website about Orchard but run by Lombiq, a company in the Orchard community.

**Comment by DeeJayTC** [comment]
Well i do need a "main" github account for that nevertheless that's the minimum we need. It can be an ORG if we add it manually but has to have a dedicated Github account.

**Comment by Piedone** [comment]
Isn't https://github.com/Lombiq that I added suitable?

**Comment by DeeJayTC** [comment]
Yea i guess that could work, let me check that

**Comment by Piedone** [comment]
Thank you!

**Pull request merged**
